window.AI_RESOURCE_DATA = {
  updatedAt: "2026-06-01",
  goals: {
    tools: 50,
    routes: 10,
    tutorials: 20
  },
  categories: [
    { id: "chat", name: "对话写作", hint: "问答、写作、翻译、资料整理" },
    { id: "search", name: "AI搜索", hint: "联网检索、信息核验、资料引用" },
    { id: "image", name: "图像设计", hint: "图片生成、海报、品牌视觉" },
    { id: "video", name: "视频创作", hint: "脚本、分镜、数字人、视频生成" },
    { id: "audio", name: "音频语音", hint: "配音、音乐、播客、转写" },
    { id: "office", name: "办公学习", hint: "文档、PPT、笔记、会议纪要" },
    { id: "coding", name: "编程开发", hint: "代码生成、调试、原型开发" },
    { id: "automation", name: "自动化", hint: "工作流、知识库、表单联动" },
    { id: "marketing", name: "营销文案", hint: "广告文案、SEO、私域内容" }
  ],
  roles: [
    { id: "student", name: "学生", summary: "论文资料、学习规划、作业辅助、语言学习" },
    { id: "ecommerce", name: "电商", summary: "选品、标题、详情页、客服、投放素材" },
    { id: "workplace", name: "职场", summary: "周报、PPT、会议纪要、方案写作" },
    { id: "operations", name: "运营", summary: "活动策划、内容日历、数据复盘、增长实验" },
    { id: "design", name: "设计", summary: "视觉灵感、海报、品牌素材、图片修补" },
    { id: "developer", name: "程序员", summary: "代码解释、重构、测试、产品原型" },
    { id: "teacher", name: "教师", summary: "教案、题库、课程大纲、课堂互动" },
    { id: "sales", name: "销售", summary: "客户研究、话术、邮件、方案跟进" },
    { id: "hr", name: "HR", summary: "招聘JD、面试题、培训材料、绩效沟通" },
    { id: "creator", name: "短视频创作者", summary: "脚本、分镜、配音、封面和剪辑" }
  ],
  tools: [
    {
      id: "chatgpt",
      name: "ChatGPT",
      vendor: "OpenAI",
      category: "chat",
      url: "https://chatgpt.com/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册，团队版本可走企业工作区",
      roles: ["student", "workplace", "operations", "developer", "teacher", "sales"],
      summary: "通用对话和多模态助手，适合写作、学习、方案、代码和资料整理。",
      scenes: ["写报告和PPT大纲", "解释概念和代码", "生成提示词和工作流"],
      pros: ["生态成熟", "适用场景广", "适合做入门主线工具"],
      cons: ["重要资料需要二次核验", "高级功能和团队能力通常需要付费"],
      alternatives: ["Claude", "Gemini", "Kimi"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "claude",
      name: "Claude",
      vendor: "Anthropic",
      category: "chat",
      url: "https://claude.ai/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱注册，部分地区和企业能力以官网开放情况为准",
      roles: ["student", "workplace", "operations", "developer", "sales"],
      summary: "长文本阅读、写作和分析能力突出，适合处理文档、方案和复杂讨论。",
      scenes: ["长文总结", "合同和资料梳理", "产品需求与代码解释"],
      pros: ["长文本体验好", "表达稳健", "适合知识工作者"],
      cons: ["地区和账号开放情况需核验", "联网和生态能力以官方版本为准"],
      alternatives: ["ChatGPT", "Gemini", "Kimi"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "gemini",
      name: "Gemini",
      vendor: "Google",
      category: "chat",
      url: "https://gemini.google.com/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "Google账号登录，企业可结合Google Workspace",
      roles: ["student", "workplace", "developer", "teacher", "creator"],
      summary: "适合结合Google生态进行搜索、写作、资料整理和多模态任务。",
      scenes: ["搜索资料后生成摘要", "处理图片和文档", "Google生态办公辅助"],
      pros: ["Google生态衔接强", "多模态能力覆盖广", "适合资料检索场景"],
      cons: ["地区可用性需核验", "中文场景建议和其他工具交叉验证"],
      alternatives: ["ChatGPT", "Claude", "Microsoft Copilot"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "copilot",
      name: "Microsoft Copilot",
      vendor: "Microsoft",
      category: "office",
      url: "https://copilot.microsoft.com/",
      pricing: "免费入口 + Microsoft 365相关付费能力，以官网为准",
      signup: "Microsoft账号登录，企业能力与Microsoft 365订阅相关",
      roles: ["workplace", "sales", "hr", "teacher"],
      summary: "适合Office文档、邮件、会议和企业办公场景。",
      scenes: ["Word和PPT辅助", "邮件草稿", "会议内容整理"],
      pros: ["办公场景贴合", "企业协作友好", "适合职场用户"],
      cons: ["完整能力可能依赖订阅", "企业配置需要管理员支持"],
      alternatives: ["ChatGPT", "Notion AI", "Gamma"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "perplexity",
      name: "Perplexity",
      vendor: "Perplexity AI",
      category: "search",
      url: "https://www.perplexity.ai/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号登录",
      roles: ["student", "workplace", "operations", "sales", "teacher"],
      summary: "面向搜索和问答的AI工具，适合快速查资料并查看来源。",
      scenes: ["行业资料搜索", "竞品调研", "论文和新闻线索整理"],
      pros: ["强调来源链接", "适合调研起步", "查询体验直接"],
      cons: ["引用质量仍需人工核验", "深度判断不能完全替代原文阅读"],
      alternatives: ["Gemini", "Kimi", "ChatGPT"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "kimi",
      name: "Kimi",
      vendor: "Moonshot AI",
      category: "chat",
      url: "https://kimi.moonshot.cn/",
      pricing: "免费额度 + 付费能力，以官网为准",
      signup: "手机号或账号登录，具体方式以页面为准",
      roles: ["student", "workplace", "operations", "teacher"],
      summary: "中文长文本阅读和资料整理场景常用，适合文件总结与学习辅助。",
      scenes: ["上传资料总结", "论文和报告提纲", "中文内容改写"],
      pros: ["中文体验友好", "适合长资料处理", "入门门槛较低"],
      cons: ["专业结论需核验", "文件和额度规则会变化"],
      alternatives: ["ChatGPT", "Claude", "通义千问"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "doubao",
      name: "豆包",
      vendor: "字节跳动",
      category: "chat",
      url: "https://www.doubao.com/",
      pricing: "免费能力 + 付费能力，以官网为准",
      signup: "手机号或第三方账号登录",
      roles: ["student", "ecommerce", "workplace", "creator", "teacher"],
      summary: "中文对话、写作、图片和生活学习场景友好，适合大众用户入门。",
      scenes: ["学习答疑", "短视频脚本", "电商文案草稿"],
      pros: ["中文使用门槛低", "适合日常内容生产", "移动端体验友好"],
      cons: ["商业素材需审核版权和事实", "高级能力以官方开放为准"],
      alternatives: ["Kimi", "通义千问", "文小言"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "qwen",
      name: "通义千问",
      vendor: "阿里云",
      category: "chat",
      url: "https://tongyi.aliyun.com/",
      pricing: "免费入口 + 云服务相关付费能力，以官网为准",
      signup: "阿里账号或手机号登录，企业可接入阿里云服务",
      roles: ["student", "ecommerce", "workplace", "developer", "operations"],
      summary: "中文通用大模型入口，适合办公、电商、开发和知识问答。",
      scenes: ["商品文案", "企业知识问答", "代码和数据说明"],
      pros: ["中文和产业生态强", "适合阿里生态用户", "可延展到云服务"],
      cons: ["不同入口能力可能不同", "企业接入需要配置"],
      alternatives: ["Kimi", "豆包", "文小言"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "wenxiaoyan",
      name: "文小言",
      vendor: "百度",
      category: "chat",
      url: "https://yiyan.baidu.com/",
      pricing: "免费入口 + 付费能力，以官网为准",
      signup: "百度账号登录",
      roles: ["student", "workplace", "operations", "teacher", "creator"],
      summary: "百度生态下的中文AI助手，适合搜索、写作、图片理解和知识问答。",
      scenes: ["中文资料检索", "办公写作", "创意内容生成"],
      pros: ["百度生态衔接", "中文本地化强", "适合搜索型内容"],
      cons: ["具体能力随版本变化", "专业资料仍需查原文"],
      alternatives: ["Kimi", "豆包", "通义千问"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "zhipu",
      name: "智谱清言",
      vendor: "智谱AI",
      category: "chat",
      url: "https://chatglm.cn/",
      pricing: "免费入口 + 付费能力，以官网为准",
      signup: "手机号或账号登录",
      roles: ["student", "workplace", "developer", "teacher"],
      summary: "中文大模型助手，适合问答、写作、办公和开发辅助。",
      scenes: ["资料问答", "方案撰写", "开发知识解释"],
      pros: ["中文使用友好", "适合国产模型对比", "场景覆盖广"],
      cons: ["额度和插件规则需核验", "重要输出需人工确认"],
      alternatives: ["DeepSeek", "Kimi", "通义千问"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "deepseek",
      name: "DeepSeek",
      vendor: "DeepSeek",
      category: "chat",
      url: "https://www.deepseek.com/",
      pricing: "以官网和API文档为准",
      signup: "官网入口或API平台按页面要求注册",
      roles: ["student", "developer", "workplace", "teacher"],
      summary: "常用于推理、代码和中文问答场景，适合学习与开发辅助。",
      scenes: ["代码解释", "数学和逻辑推理", "中文资料总结"],
      pros: ["开发者关注度高", "推理和代码场景常用", "适合模型对比内容"],
      cons: ["可用入口和额度需核验", "线上服务状态需关注官方说明"],
      alternatives: ["ChatGPT", "Claude", "智谱清言"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "poe",
      name: "Poe",
      vendor: "Quora",
      category: "chat",
      url: "https://poe.com/",
      pricing: "免费额度 + 订阅，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["student", "workplace", "creator", "developer"],
      summary: "聚合多种AI模型的对话平台，适合对比模型风格和快速试用。",
      scenes: ["多模型对比", "提示词测试", "轻量聊天机器人"],
      pros: ["模型入口集中", "适合教学演示", "切换体验方便"],
      cons: ["不同模型额度不同", "不等同于各模型官方完整能力"],
      alternatives: ["ChatGPT", "Claude", "Gemini"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "midjourney",
      name: "Midjourney",
      vendor: "Midjourney",
      category: "image",
      url: "https://www.midjourney.com/",
      pricing: "订阅制为主，以官网为准",
      signup: "按官网流程创建账号并进入生成入口",
      roles: ["design", "creator", "ecommerce", "operations"],
      summary: "高质量图像生成工具，适合视觉灵感、概念图和商业素材草案。",
      scenes: ["海报视觉探索", "产品氛围图", "角色和场景概念"],
      pros: ["图像质感强", "风格探索效率高", "适合设计灵感"],
      cons: ["商业使用需看授权规则", "中文提示词效果需测试"],
      alternatives: ["Stable Diffusion", "Leonardo AI", "即梦AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "dalle",
      name: "DALL·E",
      vendor: "OpenAI",
      category: "image",
      url: "https://openai.com/dall-e/",
      pricing: "随OpenAI产品入口和计划变化，以官网为准",
      signup: "通常通过OpenAI相关产品入口使用",
      roles: ["design", "creator", "ecommerce", "teacher"],
      summary: "图像生成能力，适合把自然语言需求转成图片草案。",
      scenes: ["课程配图", "概念图", "商品创意图"],
      pros: ["自然语言理解好", "适合和对话工作流结合", "入门门槛低"],
      cons: ["细节控制需迭代", "商用和版权需看官方政策"],
      alternatives: ["Midjourney", "Adobe Firefly", "Canva AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "stable-diffusion",
      name: "Stable Diffusion",
      vendor: "Stability AI / 开源生态",
      category: "image",
      url: "https://stability.ai/",
      pricing: "开源生态 + 云服务付费，以具体平台为准",
      signup: "可用本地部署、第三方平台或Stability相关服务",
      roles: ["design", "developer", "creator", "ecommerce"],
      summary: "图像生成开源生态，适合需要更强控制和定制的视觉工作流。",
      scenes: ["本地模型工作流", "电商模特图", "风格化批量生成"],
      pros: ["可定制空间大", "生态插件丰富", "适合进阶用户"],
      cons: ["学习成本较高", "本地部署需要硬件和配置"],
      alternatives: ["Midjourney", "Leonardo AI", "Adobe Firefly"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "leonardo",
      name: "Leonardo AI",
      vendor: "Leonardo.Ai",
      category: "image",
      url: "https://leonardo.ai/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["design", "creator", "ecommerce"],
      summary: "图像生成和创意资产平台，适合游戏、美术、电商和社媒素材。",
      scenes: ["产品视觉", "游戏素材", "社媒海报"],
      pros: ["模板和风格丰富", "适合创意资产生产", "上手较快"],
      cons: ["免费额度有限", "商用授权需核验"],
      alternatives: ["Midjourney", "Stable Diffusion", "Canva AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "canva-ai",
      name: "Canva AI",
      vendor: "Canva",
      category: "image",
      url: "https://www.canva.com/ai/",
      pricing: "免费入口 + Pro/团队能力，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["design", "ecommerce", "operations", "teacher", "creator"],
      summary: "把AI生成和在线设计结合，适合非设计人员做海报、PPT和社媒图。",
      scenes: ["公众号封面", "课程海报", "电商活动图"],
      pros: ["模板丰富", "协作方便", "适合轻设计"],
      cons: ["专业设计自由度有限", "高级素材和功能可能付费"],
      alternatives: ["Adobe Firefly", "即梦AI", "Gamma"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "firefly",
      name: "Adobe Firefly",
      vendor: "Adobe",
      category: "image",
      url: "https://www.adobe.com/products/firefly.html",
      pricing: "免费额度 + Adobe相关付费计划，以官网为准",
      signup: "Adobe账号登录",
      roles: ["design", "creator", "ecommerce"],
      summary: "Adobe生态内的生成式创意工具，适合设计师和品牌素材制作。",
      scenes: ["图片扩展", "文字效果", "商业视觉草案"],
      pros: ["Adobe生态衔接", "适合设计工作流", "品牌应用友好"],
      cons: ["完整能力可能依赖订阅", "国内访问和授权需核验"],
      alternatives: ["Midjourney", "Canva AI", "Stable Diffusion"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "jimeng",
      name: "即梦AI",
      vendor: "字节跳动",
      category: "image",
      url: "https://jimeng.jianying.com/",
      pricing: "免费额度 + 付费能力，以官网为准",
      signup: "按官网或剪映生态账号流程登录",
      roles: ["design", "creator", "ecommerce", "operations"],
      summary: "中文图像和视频创意工具，适合短视频、电商和社媒素材探索。",
      scenes: ["国风海报", "短视频分镜", "商品视觉"],
      pros: ["中文创作友好", "和内容创作场景贴近", "适合本土素材"],
      cons: ["额度和版权规则需核验", "专业控制需测试"],
      alternatives: ["Midjourney", "Canva AI", "可灵AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "runway",
      name: "Runway",
      vendor: "Runway",
      category: "video",
      url: "https://runwayml.com/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["creator", "design", "operations", "ecommerce"],
      summary: "AI视频生成和编辑平台，适合创意视频、广告片段和分镜测试。",
      scenes: ["文生视频", "图片转视频", "视频背景处理"],
      pros: ["视频生成能力强", "创意工具完整", "适合短片原型"],
      cons: ["免费额度有限", "成片稳定性需要多轮筛选"],
      alternatives: ["Pika", "可灵AI", "即梦AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "pika",
      name: "Pika",
      vendor: "Pika",
      category: "video",
      url: "https://pika.art/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["creator", "design", "ecommerce"],
      summary: "AI视频生成工具，适合短视频创意、动态海报和产品动效测试。",
      scenes: ["图片动起来", "短片创意", "社媒视频素材"],
      pros: ["上手快", "适合短视频实验", "视觉玩法多"],
      cons: ["复杂镜头需多次生成", "商用规则需核验"],
      alternatives: ["Runway", "可灵AI", "即梦AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "kling",
      name: "可灵AI",
      vendor: "快手",
      category: "video",
      url: "https://klingai.kuaishou.com/",
      pricing: "免费额度 + 付费能力，以官网为准",
      signup: "按官网流程登录，国内用户通常更易上手",
      roles: ["creator", "ecommerce", "design", "operations"],
      summary: "中文视频生成工具，适合短视频、电商素材和分镜验证。",
      scenes: ["商品短视频", "人物动态镜头", "剧情分镜"],
      pros: ["中文场景友好", "适合本土短视频内容", "图片转视频常用"],
      cons: ["额度和排队情况会变化", "商业授权需看官方规则"],
      alternatives: ["Runway", "Pika", "即梦AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "synthesia",
      name: "Synthesia",
      vendor: "Synthesia",
      category: "video",
      url: "https://www.synthesia.io/",
      pricing: "付费计划为主，以官网为准",
      signup: "邮箱注册，企业方案按官网联系",
      roles: ["teacher", "hr", "sales", "workplace"],
      summary: "数字人视频平台，适合培训、说明视频和企业内部课程。",
      scenes: ["员工培训", "产品介绍", "多语言讲解"],
      pros: ["企业培训友好", "数字人口播效率高", "多语言场景强"],
      cons: ["成本相对较高", "真人感和授权需评估"],
      alternatives: ["HeyGen", "Runway", "剪映"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "heygen",
      name: "HeyGen",
      vendor: "HeyGen",
      category: "video",
      url: "https://www.heygen.com/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["sales", "hr", "creator", "teacher"],
      summary: "数字人和视频翻译平台，适合口播、课程、营销和跨语言视频。",
      scenes: ["数字人口播", "视频翻译", "产品讲解"],
      pros: ["口播场景直接", "适合营销和培训", "模板较丰富"],
      cons: ["肖像和声音授权要谨慎", "高质量输出通常需要付费"],
      alternatives: ["Synthesia", "剪映", "Runway"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "elevenlabs",
      name: "ElevenLabs",
      vendor: "ElevenLabs",
      category: "audio",
      url: "https://elevenlabs.io/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["creator", "teacher", "sales", "operations"],
      summary: "AI语音生成和声音相关工具，适合配音、播客和多语言内容。",
      scenes: ["短视频配音", "课程旁白", "多语言音频"],
      pros: ["语音自然度高", "多语言覆盖", "适合内容团队"],
      cons: ["声音克隆需授权", "免费额度和商用规则需核验"],
      alternatives: ["剪映", "Descript", "HeyGen"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "suno",
      name: "Suno",
      vendor: "Suno",
      category: "audio",
      url: "https://suno.com/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["creator", "operations", "teacher"],
      summary: "AI音乐生成工具，适合短视频BGM、活动主题曲和创意实验。",
      scenes: ["短视频配乐", "品牌主题歌草案", "课堂音乐素材"],
      pros: ["生成速度快", "创意效果强", "适合内容灵感"],
      cons: ["商用和版权要看规则", "歌词和风格需多次迭代"],
      alternatives: ["Udio", "ElevenLabs", "剪映"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "udio",
      name: "Udio",
      vendor: "Udio",
      category: "audio",
      url: "https://www.udio.com/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["creator", "operations", "teacher"],
      summary: "AI音乐创作平台，适合音乐灵感、短视频配乐和内容实验。",
      scenes: ["音乐小样", "社媒BGM", "课程音频素材"],
      pros: ["音乐表现力强", "适合灵感探索", "可做风格对比"],
      cons: ["授权规则需核验", "稳定商业输出需要筛选"],
      alternatives: ["Suno", "ElevenLabs", "Descript"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "descript",
      name: "Descript",
      vendor: "Descript",
      category: "audio",
      url: "https://www.descript.com/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["creator", "teacher", "operations", "workplace"],
      summary: "音视频转写和剪辑工具，适合播客、访谈、课程和口播内容。",
      scenes: ["转写剪辑", "播客编辑", "字幕和脚本修订"],
      pros: ["文本式剪辑直观", "适合内容团队", "转写工作流完整"],
      cons: ["中文效果需实测", "高级功能通常付费"],
      alternatives: ["Otter.ai", "剪映", "ElevenLabs"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "capcut",
      name: "剪映 / CapCut",
      vendor: "字节跳动",
      category: "video",
      url: "https://www.capcut.com/",
      pricing: "免费入口 + 会员能力，以官网为准",
      signup: "手机号或账号登录，国内外入口可能不同",
      roles: ["creator", "ecommerce", "operations", "teacher"],
      summary: "短视频剪辑和AI辅助工具，适合社媒内容、电商短视频和课程剪辑。",
      scenes: ["自动字幕", "模板剪辑", "口播视频包装"],
      pros: ["短视频生态成熟", "模板丰富", "适合新手"],
      cons: ["平台版本能力不同", "商业素材版权需注意"],
      alternatives: ["Runway", "Descript", "可灵AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "notion-ai",
      name: "Notion AI",
      vendor: "Notion",
      category: "office",
      url: "https://www.notion.com/product/ai",
      pricing: "通常和Notion计划或AI附加能力相关，以官网为准",
      signup: "Notion账号登录",
      roles: ["student", "workplace", "operations", "hr"],
      summary: "把AI写作和知识库结合，适合笔记、项目文档和团队资料整理。",
      scenes: ["会议纪要", "知识库问答", "项目文档"],
      pros: ["知识库体验好", "适合个人和团队沉淀", "文档协作强"],
      cons: ["完整AI能力可能付费", "结构设计需要长期维护"],
      alternatives: ["飞书", "Microsoft Copilot", "ChatGPT"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "feishu",
      name: "飞书智能伙伴",
      vendor: "飞书",
      category: "office",
      url: "https://www.feishu.cn/",
      pricing: "按飞书版本和企业能力，以官网为准",
      signup: "手机号或企业账号登录",
      roles: ["workplace", "hr", "operations", "sales"],
      summary: "适合企业协作、会议纪要、文档整理和内部知识管理。",
      scenes: ["会议转写", "团队知识库", "项目协作文档"],
      pros: ["团队协作强", "适合中文企业", "办公链路完整"],
      cons: ["企业配置影响体验", "个人用户需要筛选合适入口"],
      alternatives: ["Notion AI", "Microsoft Copilot", "钉钉AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "gamma",
      name: "Gamma",
      vendor: "Gamma",
      category: "office",
      url: "https://gamma.app/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["student", "workplace", "sales", "teacher", "operations"],
      summary: "AI演示文稿和网页式文档工具，适合快速生成课程、方案和汇报。",
      scenes: ["PPT初稿", "销售方案", "课程讲义"],
      pros: ["生成速度快", "版式友好", "适合汇报原型"],
      cons: ["精修仍需人工", "品牌模板和导出能力需看计划"],
      alternatives: ["Canva AI", "Tome", "Beautiful.ai"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "tome",
      name: "Tome",
      vendor: "Tome",
      category: "office",
      url: "https://tome.app/",
      pricing: "以官网当前计划为准",
      signup: "邮箱或第三方账号注册",
      roles: ["workplace", "sales", "operations", "teacher"],
      summary: "演示和叙事型文档工具，适合商业方案、故事化汇报和内容草稿。",
      scenes: ["商业计划书", "产品故事", "课程展示"],
      pros: ["叙事表达友好", "适合创意汇报", "视觉结构清晰"],
      cons: ["功能和定位可能调整", "正式交付需人工修版"],
      alternatives: ["Gamma", "Beautiful.ai", "Canva AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "beautiful-ai",
      name: "Beautiful.ai",
      vendor: "Beautiful.ai",
      category: "office",
      url: "https://www.beautiful.ai/",
      pricing: "付费计划为主，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["workplace", "sales", "teacher", "operations"],
      summary: "偏商务演示的PPT制作工具，适合规范版式和团队模板。",
      scenes: ["企业汇报", "销售演示", "培训课件"],
      pros: ["版式规范", "商务风格稳定", "团队演示友好"],
      cons: ["灵活创作不如专业设计工具", "成本需评估"],
      alternatives: ["Gamma", "Canva AI", "Microsoft Copilot"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "cursor",
      name: "Cursor",
      vendor: "Anysphere",
      category: "coding",
      url: "https://www.cursor.com/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册，安装桌面编辑器",
      roles: ["developer", "student", "workplace"],
      summary: "AI代码编辑器，适合项目理解、代码生成、重构和调试。",
      scenes: ["读懂项目", "生成页面原型", "重构和排错"],
      pros: ["开发体验贴近IDE", "适合项目级上下文", "入门开发效率高"],
      cons: ["需要基本代码判断力", "模型和额度规则会变化"],
      alternatives: ["GitHub Copilot", "Windsurf", "Replit AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "github-copilot",
      name: "GitHub Copilot",
      vendor: "GitHub",
      category: "coding",
      url: "https://github.com/features/copilot",
      pricing: "个人、商业和企业计划，以官网为准",
      signup: "GitHub账号开通，编辑器安装插件",
      roles: ["developer", "student"],
      summary: "开发者常用AI编程助手，适合代码补全、解释和测试生成。",
      scenes: ["代码补全", "单元测试", "PR和代码解释"],
      pros: ["生态成熟", "编辑器支持广", "适合团队开发"],
      cons: ["需要关注代码安全", "复杂需求仍需开发者审查"],
      alternatives: ["Cursor", "Windsurf", "Replit AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "replit-ai",
      name: "Replit AI",
      vendor: "Replit",
      category: "coding",
      url: "https://replit.com/ai",
      pricing: "免费入口 + 付费计划，以官网为准",
      signup: "Replit账号注册后使用在线开发环境",
      roles: ["developer", "student", "teacher"],
      summary: "在线编程和AI辅助开发平台，适合教学、原型和轻量应用。",
      scenes: ["学习编程", "快速原型", "课堂演示"],
      pros: ["无需本地配置", "适合教学", "部署链路简单"],
      cons: ["大型项目受限", "成本和算力需看计划"],
      alternatives: ["Cursor", "GitHub Copilot", "v0"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "windsurf",
      name: "Windsurf",
      vendor: "Codeium",
      category: "coding",
      url: "https://windsurf.com/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册，安装编辑器",
      roles: ["developer", "student"],
      summary: "AI代码编辑器，适合项目级开发、代码修改和多文件协作。",
      scenes: ["多文件改动", "代码生成", "项目问答"],
      pros: ["适合开发者日常", "项目上下文体验好", "可做Cursor对比页"],
      cons: ["需要代码审查能力", "模型额度随计划变化"],
      alternatives: ["Cursor", "GitHub Copilot", "Replit AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "v0",
      name: "v0",
      vendor: "Vercel",
      category: "coding",
      url: "https://v0.dev/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "账号登录后通过网页生成界面代码",
      roles: ["developer", "design", "operations"],
      summary: "面向前端界面生成的AI工具，适合快速做产品原型和页面组件。",
      scenes: ["SaaS页面原型", "React组件", "后台界面草图"],
      pros: ["界面生成效率高", "适合产品原型", "和Vercel生态衔接"],
      cons: ["需要前端整合能力", "生成代码需审查和改样式"],
      alternatives: ["Cursor", "Replit AI", "Canva AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "dify",
      name: "Dify",
      vendor: "Dify",
      category: "automation",
      url: "https://dify.ai/",
      pricing: "开源版本 + 云服务计划，以官网为准",
      signup: "可用云服务注册，也可自部署",
      roles: ["developer", "operations", "workplace", "sales"],
      summary: "AI应用搭建平台，适合做知识库问答、工作流和内部助手。",
      scenes: ["企业知识库", "客服机器人", "自动化工作流"],
      pros: ["应用搭建完整", "适合团队落地", "可连接多模型"],
      cons: ["自部署需要技术能力", "知识库质量决定效果"],
      alternatives: ["Coze", "n8n", "Zapier AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "coze",
      name: "Coze",
      vendor: "字节跳动",
      category: "automation",
      url: "https://www.coze.com/",
      pricing: "免费能力 + 付费或企业能力，以官网为准",
      signup: "按官网流程创建账号和机器人",
      roles: ["operations", "developer", "ecommerce", "sales"],
      summary: "AI智能体和机器人搭建平台，适合做客服、内容助手和流程自动化。",
      scenes: ["客服机器人", "私域内容助手", "工具调用型助手"],
      pros: ["上手相对快", "智能体概念清晰", "适合运营试点"],
      cons: ["发布渠道和额度需核验", "复杂业务仍需技术配置"],
      alternatives: ["Dify", "Zapier AI", "Make"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "zapier-ai",
      name: "Zapier AI",
      vendor: "Zapier",
      category: "automation",
      url: "https://zapier.com/ai",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "Zapier账号注册后连接应用",
      roles: ["operations", "sales", "hr", "workplace"],
      summary: "把AI和常用SaaS连接起来，适合无代码自动化和消息触发。",
      scenes: ["表单自动回复", "CRM同步", "邮件摘要"],
      pros: ["连接器丰富", "适合非技术团队", "流程搭建清晰"],
      cons: ["国内工具连接需评估", "复杂流程成本可能上升"],
      alternatives: ["Make", "n8n", "Dify"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "make",
      name: "Make",
      vendor: "Make",
      category: "automation",
      url: "https://www.make.com/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱注册后创建自动化场景",
      roles: ["operations", "sales", "ecommerce", "workplace"],
      summary: "可视化自动化平台，适合把表格、邮件、表单和AI工具串起来。",
      scenes: ["订单通知", "内容分发", "客户线索跟进"],
      pros: ["流程可视化强", "连接器较多", "适合运营自动化"],
      cons: ["复杂场景需要调试", "国内应用适配需测试"],
      alternatives: ["Zapier AI", "n8n", "Coze"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "n8n",
      name: "n8n",
      vendor: "n8n",
      category: "automation",
      url: "https://n8n.io/",
      pricing: "开源自托管 + 云服务计划，以官网为准",
      signup: "可用云服务注册，也可自部署",
      roles: ["developer", "operations", "workplace"],
      summary: "自动化工作流平台，适合技术团队做可控的AI和业务流程联动。",
      scenes: ["数据同步", "AI工作流", "内部系统联动"],
      pros: ["可自托管", "扩展性强", "适合技术团队"],
      cons: ["自部署需要运维", "非技术用户学习成本高"],
      alternatives: ["Make", "Zapier AI", "Dify"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "airtable-ai",
      name: "Airtable AI",
      vendor: "Airtable",
      category: "automation",
      url: "https://www.airtable.com/platform/ai",
      pricing: "与Airtable计划相关，以官网为准",
      signup: "Airtable账号登录",
      roles: ["operations", "ecommerce", "sales", "hr"],
      summary: "把AI能力放进表格和业务数据库，适合内容库、CRM和项目管理。",
      scenes: ["内容库管理", "客户资料总结", "项目状态自动摘要"],
      pros: ["表格数据库友好", "适合内容运营", "团队协作强"],
      cons: ["中文团队需评估生态", "成本随数据和成员增加"],
      alternatives: ["Notion AI", "Zapier AI", "Make"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "jasper",
      name: "Jasper",
      vendor: "Jasper",
      category: "marketing",
      url: "https://www.jasper.ai/",
      pricing: "付费计划为主，以官网为准",
      signup: "邮箱或企业流程注册",
      roles: ["operations", "sales", "ecommerce"],
      summary: "偏营销团队的AI文案和品牌内容平台，适合广告、博客和活动文案。",
      scenes: ["广告文案", "品牌语气", "长文营销内容"],
      pros: ["营销场景聚焦", "团队品牌管理友好", "适合海外市场"],
      cons: ["中文本土效果需测试", "成本需评估"],
      alternatives: ["Copy.ai", "ChatGPT", "Canva AI"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "copy-ai",
      name: "Copy.ai",
      vendor: "Copy.ai",
      category: "marketing",
      url: "https://www.copy.ai/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["operations", "sales", "ecommerce"],
      summary: "营销文案和销售内容生成工具，适合广告、邮件和销售触达。",
      scenes: ["冷邮件", "广告标题", "产品卖点提炼"],
      pros: ["营销模板丰富", "适合销售团队", "入门快"],
      cons: ["中文和本土平台需改写", "高质量内容仍需编辑"],
      alternatives: ["Jasper", "ChatGPT", "Grammarly"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "grammarly",
      name: "Grammarly",
      vendor: "Grammarly",
      category: "marketing",
      url: "https://www.grammarly.com/",
      pricing: "免费版 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册，可安装插件",
      roles: ["student", "workplace", "sales", "hr"],
      summary: "英文写作和语法润色工具，适合邮件、论文、简历和商务沟通。",
      scenes: ["英文邮件", "简历润色", "论文语法检查"],
      pros: ["英文写作成熟", "插件生态好", "适合职场沟通"],
      cons: ["中文场景有限", "高级建议通常付费"],
      alternatives: ["QuillBot", "ChatGPT", "Claude"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "quillbot",
      name: "QuillBot",
      vendor: "QuillBot",
      category: "marketing",
      url: "https://quillbot.com/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["student", "workplace", "teacher"],
      summary: "英文改写、总结和引用辅助工具，适合学生和英文写作者。",
      scenes: ["英文改写", "摘要", "引用辅助"],
      pros: ["英文学习友好", "工具入口清晰", "适合写作训练"],
      cons: ["学术诚信需注意", "中文场景有限"],
      alternatives: ["Grammarly", "ChatGPT", "Claude"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    },
    {
      id: "otter",
      name: "Otter.ai",
      vendor: "Otter.ai",
      category: "office",
      url: "https://otter.ai/",
      pricing: "免费额度 + 付费计划，以官网为准",
      signup: "邮箱或第三方账号注册",
      roles: ["workplace", "sales", "teacher", "hr"],
      summary: "会议转写和纪要工具，适合英文会议、访谈和课堂记录。",
      scenes: ["会议纪要", "采访转写", "销售会议跟进"],
      pros: ["会议场景成熟", "摘要和协作友好", "适合英文环境"],
      cons: ["中文效果需实测", "会议隐私需确认"],
      alternatives: ["飞书", "Descript", "Microsoft Copilot"],
      updatedAt: "2026-06-01",
      sourceName: "官方主页"
    }
  ],
  tutorials: [
    {
      id: "starter-account",
      type: "入门",
      level: "新手",
      title: "AI账号注册与常见限制排查",
      audience: ["student", "workplace"],
      tools: ["ChatGPT", "Kimi", "豆包", "通义千问"],
      duration: "25分钟",
      summary: "整理账号、登录、验证、付费和地区限制的检查清单。",
      steps: ["确认官网入口", "记录注册方式和限制", "截图保存关键流程", "补充常见报错处理"],
      updatedAt: "2026-06-01"
    },
    {
      id: "prompt-basic",
      type: "入门",
      level: "新手",
      title: "提示词基础公式：角色 + 任务 + 材料 + 标准",
      audience: ["student", "workplace", "operations"],
      tools: ["ChatGPT", "Claude", "Kimi"],
      duration: "20分钟",
      summary: "把零散提问变成可复用模板，减少AI答非所问。",
      steps: ["明确目标", "给定上下文", "指定输出格式", "要求自检和追问"],
      updatedAt: "2026-06-01"
    },
    {
      id: "student-paper",
      type: "岗位",
      level: "入门",
      title: "学生论文资料整理工作流",
      audience: ["student"],
      tools: ["Kimi", "Perplexity", "ChatGPT"],
      duration: "45分钟",
      summary: "从选题、资料检索、文献摘要到提纲搭建的学习路线。",
      steps: ["拆解选题", "检索资料线索", "整理文献摘要", "生成提纲并人工改写"],
      updatedAt: "2026-06-01"
    },
    {
      id: "ecommerce-title",
      type: "岗位",
      level: "入门",
      title: "电商商品标题和详情页生成",
      audience: ["ecommerce", "operations"],
      tools: ["通义千问", "豆包", "Canva AI"],
      duration: "35分钟",
      summary: "用AI整理卖点、生成标题、优化详情页结构和活动海报。",
      steps: ["输入商品信息", "提炼核心卖点", "生成标题组合", "输出详情页模块"],
      updatedAt: "2026-06-01"
    },
    {
      id: "weekly-report",
      type: "岗位",
      level: "入门",
      title: "职场周报、月报和复盘模板",
      audience: ["workplace", "operations"],
      tools: ["ChatGPT", "Notion AI", "飞书智能伙伴"],
      duration: "30分钟",
      summary: "把零散工作记录整理成有结果、有问题、有下周计划的报告。",
      steps: ["收集工作记录", "按目标分类", "提炼成果和风险", "生成复盘和行动项"],
      updatedAt: "2026-06-01"
    },
    {
      id: "short-video-script",
      type: "案例",
      level: "入门",
      title: "短视频脚本批量生成和分镜",
      audience: ["creator", "ecommerce", "operations"],
      tools: ["豆包", "即梦AI", "剪映 / CapCut"],
      duration: "50分钟",
      summary: "从选题、脚本、分镜、口播到封面提示词的短视频生产线。",
      steps: ["确定账号定位", "生成选题池", "输出脚本和分镜", "生成封面和字幕"],
      updatedAt: "2026-06-01"
    },
    {
      id: "poster-visual",
      type: "案例",
      level: "入门",
      title: "海报和品牌视觉灵感生成",
      audience: ["design", "operations", "ecommerce"],
      tools: ["Midjourney", "Canva AI", "Adobe Firefly"],
      duration: "40分钟",
      summary: "用AI快速探索风格方向，再用设计工具做成可发布素材。",
      steps: ["定义风格关键词", "生成多组视觉", "筛选构图", "落地到海报版式"],
      updatedAt: "2026-06-01"
    },
    {
      id: "code-helper",
      type: "岗位",
      level: "进阶",
      title: "程序员用AI读代码、改Bug和写测试",
      audience: ["developer", "student"],
      tools: ["Cursor", "GitHub Copilot", "DeepSeek"],
      duration: "60分钟",
      summary: "把AI用于项目理解、问题定位、测试生成和代码审查。",
      steps: ["让AI先解释结构", "限定改动范围", "生成测试", "人工审查并运行验证"],
      updatedAt: "2026-06-01"
    },
    {
      id: "teacher-lesson",
      type: "岗位",
      level: "入门",
      title: "教师教案、题目和课堂互动生成",
      audience: ["teacher"],
      tools: ["ChatGPT", "文小言", "Gamma"],
      duration: "45分钟",
      summary: "根据教学目标生成课程大纲、例题、互动问题和课件草稿。",
      steps: ["输入年级和目标", "生成教学流程", "设计题目分层", "生成课件大纲"],
      updatedAt: "2026-06-01"
    },
    {
      id: "sales-followup",
      type: "岗位",
      level: "入门",
      title: "销售客户研究和跟进话术",
      audience: ["sales"],
      tools: ["Perplexity", "ChatGPT", "Copy.ai"],
      duration: "35分钟",
      summary: "从客户背景调研、痛点假设到邮件和微信跟进话术。",
      steps: ["整理客户信息", "生成痛点假设", "设计开场话术", "输出跟进节奏"],
      updatedAt: "2026-06-01"
    },
    {
      id: "hr-jd",
      type: "岗位",
      level: "入门",
      title: "HR招聘JD和面试题生成",
      audience: ["hr"],
      tools: ["ChatGPT", "飞书智能伙伴", "Notion AI"],
      duration: "30分钟",
      summary: "把岗位需求整理成JD、面试问题、评分表和候选人沟通模板。",
      steps: ["拆解岗位能力", "生成JD", "设计面试题", "输出评分表"],
      updatedAt: "2026-06-01"
    },
    {
      id: "search-verify",
      type: "入门",
      level: "新手",
      title: "AI搜索资料核验方法",
      audience: ["student", "workplace", "teacher", "sales"],
      tools: ["Perplexity", "Gemini", "Kimi"],
      duration: "25分钟",
      summary: "用来源、日期、原文和交叉验证减少错误引用。",
      steps: ["先问结论", "打开来源", "检查日期", "用第二工具交叉验证"],
      updatedAt: "2026-06-01"
    },
    {
      id: "knowledge-base",
      type: "进阶",
      level: "进阶",
      title: "个人或团队AI知识库搭建",
      audience: ["workplace", "operations", "developer"],
      tools: ["Dify", "Notion AI", "飞书智能伙伴"],
      duration: "75分钟",
      summary: "把资料、制度、FAQ和案例整理成可问答的知识库。",
      steps: ["清理文档", "设计分类", "导入知识库", "测试高频问题"],
      updatedAt: "2026-06-01"
    },
    {
      id: "automation-form",
      type: "进阶",
      level: "进阶",
      title: "表单收集到AI自动回复",
      audience: ["operations", "sales", "ecommerce"],
      tools: ["Make", "Zapier AI", "Coze"],
      duration: "70分钟",
      summary: "让表单、表格、AI和邮件或企微形成自动化线索处理流程。",
      steps: ["设计表单字段", "连接表格", "生成AI回复", "推送给负责人"],
      updatedAt: "2026-06-01"
    },
    {
      id: "image-prompt",
      type: "提示词",
      level: "入门",
      title: "图片生成提示词模板",
      audience: ["design", "creator", "ecommerce"],
      tools: ["Midjourney", "即梦AI", "Leonardo AI"],
      duration: "30分钟",
      summary: "用主体、场景、风格、镜头、光线和比例组织图片提示词。",
      steps: ["确定主体", "描述场景", "加入风格和镜头", "固定比例和用途"],
      updatedAt: "2026-06-01"
    },
    {
      id: "video-storyboard",
      type: "提示词",
      level: "进阶",
      title: "视频生成分镜提示词模板",
      audience: ["creator", "ecommerce", "operations"],
      tools: ["Runway", "Pika", "可灵AI"],
      duration: "45分钟",
      summary: "把视频需求拆成镜头、运动、主体、时长和转场。",
      steps: ["写一句核心剧情", "拆成3到5个镜头", "定义镜头运动", "生成并筛选素材"],
      updatedAt: "2026-06-01"
    },
    {
      id: "voice-workflow",
      type: "案例",
      level: "入门",
      title: "AI配音和播客工作流",
      audience: ["creator", "teacher", "operations"],
      tools: ["ElevenLabs", "Descript", "剪映 / CapCut"],
      duration: "45分钟",
      summary: "从脚本、配音、转写、字幕到发布的音频内容流程。",
      steps: ["生成脚本", "选择声音", "合成配音", "剪辑字幕并导出"],
      updatedAt: "2026-06-01"
    },
    {
      id: "ppt-workflow",
      type: "案例",
      level: "入门",
      title: "AI生成PPT初稿再人工精修",
      audience: ["workplace", "teacher", "sales", "student"],
      tools: ["Gamma", "Canva AI", "Microsoft Copilot"],
      duration: "45分钟",
      summary: "先用AI生成结构和页面，再按品牌、数据和讲述逻辑精修。",
      steps: ["确认听众和目标", "生成大纲", "生成页面", "人工补充数据和案例"],
      updatedAt: "2026-06-01"
    },
    {
      id: "privacy-risk",
      type: "FAQ",
      level: "必看",
      title: "AI使用隐私、版权和事实风险",
      audience: ["student", "workplace", "ecommerce", "creator"],
      tools: ["所有工具"],
      duration: "20分钟",
      summary: "整理不能上传的资料、需标注的素材和必须人工核验的内容。",
      steps: ["识别敏感信息", "检查素材授权", "核验事实来源", "保留人工审批"],
      updatedAt: "2026-06-01"
    },
    {
      id: "weekly-sop",
      type: "运营",
      level: "站长",
      title: "每周内容更新SOP",
      audience: ["operations"],
      tools: ["Airtable AI", "Notion AI", "ChatGPT"],
      duration: "30分钟",
      summary: "每周新增5个工具、更新3篇教程、补1条岗位路线。",
      steps: ["收集工具变化", "更新字段和截图", "发布新教程", "记录搜索词和点击"],
      updatedAt: "2026-06-01"
    }
  ],
  routes: [
    {
      id: "student",
      title: "学生学习与论文路线",
      audience: "学生",
      goal: "把AI变成资料整理、学习规划和表达训练助手。",
      tools: ["Kimi", "Perplexity", "ChatGPT", "QuillBot"],
      steps: ["先学提示词基础", "用AI搜索找资料线索", "用长文本工具整理文献", "人工改写和核验引用"],
      output: "选题表、文献摘要、论文提纲、答辩问题清单"
    },
    {
      id: "ecommerce",
      title: "电商运营提效路线",
      audience: "电商",
      goal: "覆盖选品、标题、详情页、客服、活动和短视频素材。",
      tools: ["通义千问", "豆包", "Canva AI", "剪映 / CapCut"],
      steps: ["整理商品卖点", "生成标题和详情页", "做活动图和短视频脚本", "沉淀客服FAQ"],
      output: "商品标题库、详情页结构、活动素材、客服话术"
    },
    {
      id: "workplace",
      title: "职场办公路线",
      audience: "职场",
      goal: "让报告、纪要、方案和PPT从零散输入变成结构化输出。",
      tools: ["ChatGPT", "Microsoft Copilot", "Notion AI", "Gamma"],
      steps: ["建立周报模板", "会议纪要自动整理", "生成方案大纲", "把内容转成PPT初稿"],
      output: "周报、复盘、方案、PPT初稿"
    },
    {
      id: "operations",
      title: "内容运营路线",
      audience: "运营",
      goal: "用AI搭建选题、排期、内容生成、复盘的闭环。",
      tools: ["ChatGPT", "Perplexity", "Canva AI", "Make"],
      steps: ["收集行业热点", "生成选题池", "批量生成初稿", "自动整理数据复盘"],
      output: "选题表、内容日历、发布素材、复盘报告"
    },
    {
      id: "design",
      title: "设计与视觉路线",
      audience: "设计",
      goal: "把AI用于风格探索、素材生成、版式提案和商业落地。",
      tools: ["Midjourney", "Adobe Firefly", "Canva AI", "Stable Diffusion"],
      steps: ["建立风格词库", "生成视觉方向", "筛选可落地方案", "进入设计工具精修"],
      output: "风格板、海报草案、产品视觉、品牌素材"
    },
    {
      id: "developer",
      title: "程序员AI开发路线",
      audience: "程序员",
      goal: "提升读代码、写代码、测代码和做产品原型的效率。",
      tools: ["Cursor", "GitHub Copilot", "DeepSeek", "v0"],
      steps: ["让AI解释项目结构", "限定范围生成代码", "补测试和文档", "人工审查并运行验证"],
      output: "功能原型、代码解释、测试用例、重构方案"
    },
    {
      id: "teacher",
      title: "教师备课路线",
      audience: "教师",
      goal: "快速生成教案、题目、互动环节和课件结构。",
      tools: ["ChatGPT", "文小言", "Gamma", "剪映 / CapCut"],
      steps: ["输入课程标准", "生成教案结构", "设计分层题目", "生成课件和视频素材"],
      output: "教案、题库、课件初稿、课堂互动问题"
    },
    {
      id: "sales",
      title: "销售增长路线",
      audience: "销售",
      goal: "提升客户研究、触达话术、方案和跟进效率。",
      tools: ["Perplexity", "Copy.ai", "ChatGPT", "Gamma"],
      steps: ["调研客户背景", "提炼痛点假设", "生成触达话术", "制作方案和跟进邮件"],
      output: "客户画像、沟通话术、销售方案、跟进节奏"
    },
    {
      id: "hr",
      title: "HR招聘与培训路线",
      audience: "HR",
      goal: "把招聘、面试、培训和制度沟通做成模板库。",
      tools: ["飞书智能伙伴", "ChatGPT", "Notion AI", "Synthesia"],
      steps: ["生成岗位JD", "设计面试题和评分表", "整理培训材料", "制作数字人培训视频"],
      output: "JD、面试题、培训课件、制度说明"
    },
    {
      id: "creator",
      title: "短视频创作者路线",
      audience: "短视频创作者",
      goal: "从选题、脚本、画面、配音到剪辑形成稳定流水线。",
      tools: ["豆包", "即梦AI", "可灵AI", "ElevenLabs", "剪映 / CapCut"],
      steps: ["确定账号定位", "生成选题和脚本", "生成分镜和素材", "配音剪辑并复盘数据"],
      output: "选题库、脚本、分镜、封面、成片"
    }
  ],
  industries: [
    {
      id: "electrical",
      name: "电气工程",
      keywords: ["电气", "电力", "强电", "配电", "dianqi", "dianli"],
      audience: "电气工程师、设备运维、电力设计助理、自动化技术员",
      goal: "用AI辅助规范查询、方案说明、设备选型资料整理和故障排查记录，但不替代专业计算与安全审核。",
      tools: ["ChatGPT", "Claude", "Kimi", "Perplexity", "Microsoft Copilot"],
      scenarios: ["配电柜方案说明", "PLC与传感器资料整理", "电气图纸审查清单", "故障现象到排查步骤"],
      prompts: ["把设备参数整理成选型对比表", "根据现场故障描述生成排查记录模板", "把电气规范条款改写成培训讲义"],
      risks: ["不能让AI直接决定线径、保护整定和安全距离", "标准版本、地区规范和设备手册必须人工核验", "涉及强电、高压、消防和人身安全必须由持证专业人员复核"]
    },
    {
      id: "machinery",
      name: "机械制造",
      keywords: ["机械", "制造", "设备", "工艺", "jixie", "zhizao"],
      audience: "机械工程师、工艺工程师、设备维护、制造业产品经理",
      goal: "用AI整理机械结构资料、工艺流程、BOM说明、维护SOP和培训材料。",
      tools: ["ChatGPT", "Kimi", "Claude", "Notion AI", "Gamma"],
      scenarios: ["设备维护手册", "零部件BOM解释", "加工工艺卡草稿", "机械结构培训课件"],
      prompts: ["把设备说明书整理成维修SOP", "把BOM清单转成采购和装配说明", "生成新员工机械安全培训大纲"],
      risks: ["尺寸、公差、材料牌号和热处理参数必须以图纸和标准为准", "AI不能替代有限元分析、工艺验证和现场试制", "涉及设备安全联锁和运动机构防护必须人工复核"]
    },
    {
      id: "automation",
      name: "工业自动化",
      keywords: ["自动化", "PLC", "产线", "智能制造", "zidonghua", "plc"],
      audience: "自动化工程师、PLC工程师、产线技术员、智能制造顾问",
      goal: "用AI辅助需求拆解、控制逻辑说明、报警字典、点位表和调试记录。",
      tools: ["ChatGPT", "DeepSeek", "Cursor", "Dify", "飞书智能伙伴"],
      scenarios: ["PLC逻辑说明", "HMI报警文案", "产线调试记录", "传感器点位表"],
      prompts: ["根据工艺流程生成控制逻辑说明", "把报警代码整理成维修知识库", "生成FAT/SAT测试清单"],
      risks: ["AI生成的控制逻辑不能直接上机运行", "联锁、急停和安全回路必须按标准设计", "现场调试记录需保留版本和责任人"]
    },
    {
      id: "construction",
      name: "建筑工程",
      keywords: ["建筑", "施工", "造价", "BIM", "jianzhu", "shigong"],
      audience: "施工管理、造价助理、资料员、BIM助理",
      goal: "用AI辅助施工方案、资料归档、会议纪要、材料清单和安全交底。",
      tools: ["Kimi", "ChatGPT", "Microsoft Copilot", "Gamma", "Canva AI"],
      scenarios: ["施工方案初稿", "安全交底材料", "会议纪要", "材料进场检查清单"],
      prompts: ["把会议录音摘要成施工待办", "生成安全交底PPT大纲", "把材料清单整理成验收表"],
      risks: ["规范条文、图纸版本和现场签证必须核验", "造价、结构安全和施工组织不能只依赖AI", "涉密项目资料不能上传到公开AI工具"]
    },
    {
      id: "medical",
      name: "医疗健康",
      keywords: ["医疗", "健康", "医学", "科普", "yiliao", "jiankang"],
      audience: "医疗运营、健康科普创作者、诊所管理、医学生",
      goal: "用AI辅助医学科普、患者教育材料、流程说明和学习笔记，不做诊断替代。",
      tools: ["ChatGPT", "Claude", "Perplexity", "Kimi", "Canva AI"],
      scenarios: ["健康科普文章", "患者宣教单", "医学学习卡片", "门诊流程说明"],
      prompts: ["把专业术语改写成患者能懂的说明", "生成健康科普短视频脚本", "整理疾病学习笔记框架"],
      risks: ["不能用AI替代医生诊断、处方和治疗决策", "医学信息必须核验指南、药品说明书和最新文献", "不得上传患者隐私和可识别病例信息"]
    },
    {
      id: "finance-legal",
      name: "财税法务",
      keywords: ["财税", "法务", "合同", "会计", "caishui", "fawu"],
      audience: "会计、财税顾问、法务助理、企业经营者",
      goal: "用AI辅助政策摘要、合同初审清单、发票流程说明和风险提示。",
      tools: ["ChatGPT", "Claude", "Kimi", "Perplexity", "Microsoft Copilot"],
      scenarios: ["合同审查清单", "税务政策摘要", "报销制度说明", "企业合规培训"],
      prompts: ["把合同条款整理成风险清单", "把税务政策改写成员工培训材料", "生成报销流程FAQ"],
      risks: ["不能把AI输出当作正式法律或税务意见", "法规时效、地区口径和合同原文必须人工核验", "涉及客户、合同和财务数据要做脱敏处理"]
    }
  ],
  videoSubmissions: [],
  comparisons: [
    {
      title: "ChatGPT vs Claude",
      keyword: "ChatGPT和Claude哪个好、长文写作用哪个AI",
      conclusion: "ChatGPT适合通用生态和多场景，Claude适合长文阅读、写作和复杂资料分析。"
    },
    {
      title: "Midjourney vs 即梦AI",
      keyword: "Midjourney和即梦AI区别、AI画图工具推荐",
      conclusion: "Midjourney适合高质感视觉探索，即梦AI更适合中文内容和本土短视频素材。"
    },
    {
      title: "Runway vs 可灵AI",
      keyword: "AI视频生成工具哪个好、Runway可灵AI对比",
      conclusion: "Runway适合国际化创意视频工作流，可灵AI适合中文短视频和电商场景测试。"
    },
    {
      title: "Gamma vs Canva AI",
      keyword: "AI做PPT工具、Gamma和Canva哪个好",
      conclusion: "Gamma适合快速生成演示结构，Canva AI适合在模板和视觉素材上继续美化。"
    },
    {
      title: "Cursor vs GitHub Copilot",
      keyword: "AI编程工具推荐、Cursor和Copilot区别",
      conclusion: "Cursor偏项目级AI编辑器，Copilot适合已有开发环境里的代码补全和团队开发。"
    },
    {
      title: "Dify vs Coze",
      keyword: "AI智能体平台、Dify和Coze哪个好",
      conclusion: "Dify适合知识库和可控应用搭建，Coze适合快速做机器人和运营场景试点。"
    }
  ],
  updateTemplate: [
    "工具名称：",
    "官网链接：",
    "注册方式：",
    "是否免费：",
    "适合岗位：",
    "主要场景：",
    "优点：",
    "限制：",
    "替代工具：",
    "最后更新时间：",
    "信息来源："
  ].join("\n")
};
